### ISSUE TITLE
Doesn't build

### ISSUE THREAD

**Issue by dagostinelli** [rpvelloso/oneheader#1]
It doesn't build on Fedora.  

I suggest:
- adding a Makefile
- add a Travis CI automatic build that calls the Makefile

The Travis CI will prove that it does compile one way or another and will also serve as a reference.

Also, the build line you recommended contains experimental C++ extensions (read: not actually 100% standard yet), this could be the source of my compilation issues.  I recommend backing off the standard somewhat and use something older (thus, will probably work).

`$ g++ -Wall -ggdb -std=c++1y -lstdc++fs oneheader.cpp -o oneheader`

Error is:

`/usr/include/c++/8/experimental/bits/fs_path.h:199: undefined reference to `std::experimental::filesystem::v1::__cxx11::path::_M_split_cmpts()'`

**Comment by rpvelloso** [comment]
@dagostinelli,

I'm really sorry for the delay, I'm only seeing this issue now, I think I've disabled notifications. Do you still need to use it and/or have problems compiling it?

**Comment by dagostinelli** [comment]
I don't need it anymore. I ended up writing my own in python.  

But I still advise you to setup a TravisCI build to avoid this.

**Comment by rpvelloso** [comment]
ok, thanks for the heads up. Care to share your python impl?
